-- DROP TABLE comments;
-- DROP TABLE posts;

CREATE TABLE posts
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(60) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT(1) DEFAULT 0
);

CREATE TABLE comments
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  post_id INTEGER NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(60) NOT NULL,
  deleted TINYINT(1) DEFAULT 0,
  CONSTRAINT fk_posts_comments_post_id FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
